# Generated by Django 5.0.3 on 2024-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultTrain',
            fields=[
                ('vaultId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('submap', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
