# Generated by Django 5.0.3 on 2024-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaulttrain',
            name='destination',
            field=models.CharField(default='Commonwealth', max_length=30),
        ),
    ]
