# Generated by Django 5.0.3 on 2024-03-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtart', '0002_vaulttrain_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaulttrain',
            name='logo',
            field=models.CharField(default='To define', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaulttrain',
            name='destination',
            field=models.CharField(default='To define', max_length=30),
        ),
    ]
